version: '3.9'

services:
  mysql:
    image: mysql:8.0.38
    restart: unless-stopped
    networks:
      - monsterTrainer
    environment:
      MYSQL_ROOT_PASSWORD: Gudmord92!
      MYSQL_DATABASE: monster_trainer
      MYSQL_USER: mtDbUser
      MYSQL_PASSWORD: Gudmord92!
    ports:
      - "3306:3306"
    volumes:
      - db:/lib/mysql
  api:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    networks:
      - monsterTrainer
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/monster_trainer?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mtDbUser
      SPRING_DATASOURCE_PASSWORD: Gudmord92!

    stdin_open: true
    tty: true
networks:
  monsterTrainer:

volumes:
  db: