spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monster-trainer-db
    username: root
    password: Gudmord92!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
